[workspace]
resolver = "2"
default-members = ["packages/web"]
members = [
    "packages/dioxus-authentication-component",
    "packages/ui",
    "packages/web",
    "packages/desktop",
]

[workspace.dependencies]
dioxus = { version = "0.7.7", features = ["router"] }

# workspace
authentication = { path = "packages/dioxus-authentication-component" }
ui = { path = "packages/ui" }
